FROM golang:1.20.7

WORKDIR /app

COPY src .

RUN go get github.com/gin-gonic/gin
RUN go get github.com/lib/pq
RUN go get github.com/sirupsen/logrus

RUN go build -o my-go-server .

EXPOSE 8080

CMD ["./my-go-server"]