version: '3'
services:
  server:
    image: go_server
    networks:
      - mynetwork
    ports:
      - "8080:8080"
      - "5432:5432"

  application:
    image: app
    networks:
      - mynetwork
    ports:
      - "8501:8501"

networks:
  mynetwork:
