apiVersion: v1
kind: Service
metadata:
  name: python-frontend-service
spec:
  selector:
    app: python-frontend
  ports:
    - protocol: TCP
      port: 8501  # Port exposed within the cluster
      targetPort: 8501  # Port the frontend application is listening on
  type: NodePort
